name: CI/CD

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive
      - name: Setup Rust
        uses: MatteoH2O1999/setup-rust@v1
        with:
          channel: stable
          profile: minimal
          components: clippy rustfmt
      - name: Check code formatting
        run: cargo fmt -- --check
      - name: Build clippy
        run: cargo clippy
      - name: Check clippy lint
        run: cargo clippy -- -Dwarnings

  docs:
    name: Check docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive
      - name: Setup Rust
        uses: MatteoH2O1999/setup-rust@v1
        with:
          channel: stable
          profile: minimal
          components: rust-docs
      - name: Check docs
        run: cargo doc
        env:
          RUSTDOCFLAGS: -D warnings

  tests:
    name: Unit tests on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive
      - name: Setup Rust
        uses: MatteoH2O1999/setup-rust@v1
        with:
          channel: stable
          profile: minimal
      - name: Test build
        run: cargo build --release
      - name: Build tests
        run: cargo test --no-run
      - name: Run tests
        run: cargo test

  miri:
    name: Check for UB on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive
      - name: Setup Rust
        uses: MatteoH2O1999/setup-rust@v1
        with:
          channel: nightly
          profile: minimal
          components: miri
      - name: Build tests
        run: |
          cargo miri setup
          cargo test --no-run
      - name: Run tests
        run: cargo miri test

  api:
    name: Check semver and MSV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive
      - name: Setup Rust
        uses: MatteoH2O1999/setup-rust@v1
        with:
          channel: stable
          profile: minimal
      - name: Install cargo-quickinstall
        run: cargo install cargo-quickinstall
      - name: Install cargo-semver-checks and cargo-msrv
        run: cargo quickinstall cargo-semver-checks cargo-msrv
      - name: Check semver compatibility
        run: cargo semver-checks
      - name: Check minimum Rust version
        run: |
          cargo msrv set 1.56
          cargo msrv find --write-msrv --ignore-lockfile
          git diff --exit-code

  publish:
    needs: [api, docs, lint, tests, miri]
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive
      - name: Setup Rust
        uses: MatteoH2O1999/setup-rust@v1
        with:
          channel: stable
          profile: minimal
      - name: Test publishing
        if: ${{ github.event_name != 'release' }}
        run: cargo publish --dry-run -v
      - name: Publish package
        if: ${{ github.event_name == 'release' }}
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
